---
# parser: eslint
parser: vue-eslint-parser
parserOptions:
    parser: babel-eslint

extends:
  - airbnb-base
  - plugin:jasmine/recommended
  - plugin:vue/recommended

plugins:
  - jasmine
  - babel
  - vue
  - ramda

env:
  browser: true
  es6: true
  jquery: true
  jasmine: true
  node: true

globals:
  _: true
  Î»: true
  Pusher: true
  integer: true
  string: true
  required: true
  boolean: true
  array: true
  min: true
  max: true
  equals: true
  object: true
  any: true
  CodeMirror: true

rules:
  camelcase: 0
  no-confusing-arrow: 0
  no-return-assign: 0
  class-methods-use-this: 0
  eol-last: ["error", "never"]
  indent: ["error", 4]
  no-mixed-spaces-and-tabs: 2
  no-param-reassign: 0
  no-underscore-dangle: 0
  no-restricted-globals: 0
  lines-between-class-members: 0
  space-before-function-param: 0
  space-before-function-paren: 0
  no-trailing-spaces: 2
  no-console: 0
  semi: 0
  operator-linebreak: 0
  one-var: 0
  one-var-declaration-per-line: 0
  babel/new-cap: 1
  babel/camelcase: 0
  babel/no-invalid-this: 1
  babel/object-curly-spacing: 0
  babel/quotes: 0
  babel/semi: 0
  babel/no-unused-expressions: 1
  babel/valid-typeof: 1
  vue/attributes-order: 0
  vue/html-closing-bracket-newline: 0
  vue/html-indent: ["error", 4]
  vue/html-self-closing: 0
  vue/max-attributes-per-line: 0
  vue/require-default-prop: 0
  vue/component-name-in-template-casing: 0
  vue/singleline-html-element-content-newline: 0
  vue/multiline-html-element-content-newline: 0
  # arrow-body-style: 0
  # func-names: 0
  # space-before-function-paren: 0
  # no-restricted-syntax: 0

# npx install-peerdeps -g eslint-config-airbnb
# npm install -g eslint eslint-plugin-vue@next eslint-plugin-jasmine \
#                eslint-config-airbnb eslint-config-airbnb-base \
#                eslint-plugin-import@latesteeslint-plugin-html
#
# Optional:
#
# npm install -g eslint_d
